# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IoT-Project' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'CocoaMQTT' 
  # Pods for IoT-Project

  target 'IoT-ProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IoT-ProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
